[[services]]
title = "opendkim"
exec = "/usr/sbin/opendkim"
args = ["-x", "-f", "-x", "/etc/opendkim/opendkim.conf", "-d", "all"]
essential = true

[[services]]
title = "syslogd"
exec = "/usr/sbin/rsyslogd"
args = ["-n", "-O", "/dev/stderr"]
